# Generated by Django 3.2.10 on 2022-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.AddField(
            model_name='songs',
            name='songlink',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='songs',
            name='songname',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
